/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com;

import com.revature.controllers.ReimbursementController;
import com.revature.controllers.UserController;
import com.revature.dao.IReimbursementDao;
import com.revature.dao.IUserDao;
import com.revature.dao.ReimbursementDao;
import com.revature.dao.UserDao;
import com.revature.services.ReimbursementServices;
import com.revature.services.UserServices;
import io.javalin.Javalin;
import static io.javalin.apibuilder.ApiBuilder.*;

public class App {

    public static void main(String args[]){
        IUserDao ud = new UserDao();
        UserServices us = new UserServices(ud);
        UserController uc = new UserController(us);

        IReimbursementDao rd = new ReimbursementDao();
        ReimbursementServices rs = new ReimbursementServices(rd);
        ReimbursementController rc = new ReimbursementController(rs);

        // javalin app
        Javalin server = Javalin.create(config -> {config.enableCorsForAllOrigins();});

        server.routes(()-> {
            path("users", () -> {
                post("/login", uc.handleUserLogin);
                get("/logout", uc.handleUserLogout);
                post("/register", uc.handleUserRegistration);
                put("/update", uc.handleUpdateUser);
                delete("/delete/{id}", uc.handleDeleteUser);
                get("/view/{id}", uc.handleViewUserById);
                get("/viewall", uc.handleViewAllUsers);
            });
            path("reimbursement", () -> {
                post("/register", rc.handleAddReimbursement);
                put("/update", rc.handleUpdateReimbursement);
                delete("/delete/{id}", rc.handleDeleteReimbursement);
                get("/view/{id}", rc.handleViewReimbursement);
                post("/viewbyuser", rc.handleViewReimbursementsByUser);
                get("/viewall", rc.handleViewAllReimbursements);
            });
        });

        server.start(8000);


        //test createUser
        //User dawit = new User("dawit", "password", "dawit", "alemu", "dawits.alemu@mail.com", 2);
        //User result = ud.createUser(dawit);
        //System.out.println(result);*/

        //test viewUser
        /*User result = ud.viewUser(5);
        System.out.println(result);*/

        //test updateUser
        /*User dawit = new User(5, "dawit", "password", "dawit", "alemu", "dawits.alemu@revature.com", 2);
        ud.updateUser(dawit);*/

        //test deleteUser
        //ud.deleteUser(5);

        //test createReimbursement
        /*BigDecimal bd = new BigDecimal(100.00);
        Reimbursement reimbursement = new Reimbursement(bd, Date.valueOf(LocalDate.now()), null, "test", 4, 4, 1, 1);
        Reimbursement result = rd.createReimbursement(reimbursement);
        System.out.println(result); */

        //test viewReimbursement
        /*Reimbursement result = rd.viewReimbursement(2);
        System.out.println(result);*/

        //test updateReimbursement
        /*BigDecimal bd = new BigDecimal(100.00);
        Reimbursement reimbursement = new Reimbursement(2, bd, Date.valueOf(LocalDate.now()), null, "test", 4, 6, 1, 1);
        rd.updateReimbursement(reimbursement);*/

        //test deleteReimbursement
        //rd.deleteReimbursement(2);

        //UserServices us = new UserServices(ud);

        //User result = us.createUser(dawit);

        //System.out.println(result);
    }

}